# Application Configuration Settings:
Application:
    Name: "Test App"
    Version: [0, 0, 1]

Window:
    Label: "Test Game"
    Extent: [1600, 900]
    Mode: 0
    IsResizable: false
    VsyncEnabled: false

SceneManager:
  StartScene:
    Runtime: "Test"
    Editor: "Test"
  SceneMap:
    - Name: "Test"
      Path: "TestScene.yaml"