# PBR Application Settings

# Asset Pack for all Shaders and Default Assets.
Assets:
  # Shaders:
- AssetID: 1000
  TypeID: 3541022837009731048
  Path: "GridShader.yaml"
- AssetID: 1001
  TypeID: 3541022837009731048
  Path: "SkyboxShader.yaml"
- AssetID: 1002
  TypeID: 3541022837009731048
  Path: "PBRShader.yaml"
- AssetID: 1003
  TypeID: 3541022837009731048
  Path: "ShadowPass.yaml"
  # Textures
- AssetID: 10
  TypeID: 2829778445906215252
  Path: "Images\\ErrorTexture.png"
- AssetID: 11
  TypeID: 2829778445906215252
  Path: "Images\\BlackTexture.png"
- AssetID: 12
  TypeID: 2829778445906215252
  Path: "Images\\WhiteTexture.png"
- AssetID: 13
  TypeID: 2829778445906215252
  Path: "Images\\FlatNormalTexture.png"
  # Default Skybox
- AssetID: 500
  TypeID: 17573926464023591641
  Path: "Skybox\\Skybox.yaml"
  # Materials
- AssetID: 5000
  TypeID: 14967253334840397702
  Path: "Materials\\DefaultMaterial.yaml"

DefaultAssetIDs:
  ErrorTextureID: 10
  BlackTextureID: 11
  WhiteTextureID: 12
  FlatNormalTextureID: 13
  DefaultSkyboxID: 500
  DefaultMaterialID: 5000

RenderTargets:
  Color:
    Format: 0       # Unknown to use supported Swapchain format.
    SampleCount: 0  # Zero to use the max supported by the format.
    ClearColor: [0.01, 0.01, 0.01, 1.0]
    Size: [0, 0]    # Zero size to use the swapchain dimensions.
    Usage: 4        # EImageUsageBits::ColorAttachment (4)
  Depth:
    FormatMinBits: 24
    FormatRequireStencil: true  
    SampleCount: 0      # Zero to use the max supported by depth format.
    ClearDepth: 1.0
    ClearStencil: 0
    Size: [0, 0]        # Zero size to use the swapchain dimensions.
    Usage: 8            # EImageUsageBits::DepthStencilAttachment (8)

ShadowSettings:
  DepthShader: 1003
  FormatMinBits: 32
  NumCascades: 4            # How many cascades to generate. [1, 4]
  MaxShadowDistance: 100.0  # Objects past this distance from the camera will not have shadows.
  ImageResolution: 4096       # WxH of the first cascade.
  CascadeSplitLambda: 0.5
  DepthBiasConstant: 0.0
  DepthBiasSlope: 0.0

Pipelines:
  Grid: "Pipelines\\GridPipeline.yaml"
  Skybox: "Pipelines\\SkyboxPipeline.yaml"
  PBR: "Pipelines\\PBRPipeline.yaml"

